### ISSUE TITLE
Data corruption bug

### ISSUE THREAD

**Issue by nift4** [HelloVolla/android-launcher-qt#27] opened 2020-12-16 06:24 UTC
![Pic](https://user-images.githubusercontent.com/36458596/102312722-862dcb80-3f6f-11eb-95c6-fa08e8a7df28.png)

This happens for me when using the multi-user functionality, but this picture from another user doesn't seem to be caused by multi-user.

The only fix is deleting data from the Volla Launcher

**Comment by wurzer** [comment] 2020-12-17 21:56
This looks like an old version of the Volla Launcher. Please have a look, that you have the recent version 1.2.x

**Comment by nift4** [comment] 2021-01-11 09:03
I just reproduced the problem on 1.2.1 my using multi-user with a guest account then switching back to the main one

**Comment by SimplyComple0x78** [comment] 2021-01-31 13:05
This also showed up for me trying out the multi-user functionality just for fun.

Steps to reproduce (in 1.2.1 as above):
1. Make sure you're currently in the Administrator's profile under "System" -> "Mehrere Nutzer" (multi-user)
2. Under "System" -> "Mehrere Nutzer" (multi-user), switch to User "Guest", wait for setup, choose "Volla" from the drawer and grant access-rights. Since now, everything works.
3. Under "System" -> "Mehrere Nutzer" (multi-user), the Administrator's profile can not be selected (i guess that's ok?) and the only option is "Gast entfernen" (remove the Guest).
4. Click "Gast entfernen" (remove the Guest), confirm and wait for switch.
5. Now it's broken, the "Home"-Button shows the broken screen

The [screenshot i took](https://user-images.githubusercontent.com/876742/106384772-de5c4800-63cc-11eb-9d6f-2104b440236f.png) is identical to what @nift4 gave us.

Maybe @wurzer has any idea looking at the [log-output I got](https://github.com/HelloVolla/android-launcher-qt/files/5899746/issue-27.log)

**Comment by wurzer** [comment] 2022-06-14 21:11
Should be solved in recent release.

**Comment by wurzer** [comment] 2022-09-03 17:27
Should be fixed since some releases

**Closed by wurzer** 2022-09-03 17:27 UTC
Labels: bug
