### ISSUE TITLE
Springboard emoji misplaced

### ISSUE THREAD

**Issue by StaffanMelin** [HelloVolla/android-launcher-qt#203] opened 2023-12-12 15:41 UTC
If you use emojis in the springboard, they are not placed correctly, too low, and the bottom is cut off.
![volla_springboard_emojis](https://github.com/HelloVolla/volla-os-beta-test/assets/33361311/0449f2cf-b318-4c14-a799-32d51e51e692)

BTW. It is not obvious that you need to hold down Enter to enter emoji mode, but maybe that is the fault of the AOSP keyboard.

**Comment by wurzer** [comment] 2024-04-28 16:16
Can reproduce it. @erfanoabdi Looks like a font issue of Volla OS 13. Can't reproduce it on Volla OS 12

**Comment by wurzer** [comment] 2024-09-14 20:36
Fixed in recent release

**Closed by wurzer** 2024-09-14 20:36 UTC
Labels: bug
